UMLTeam/DearHouAimin

- src/main/webapp/js/index/index.js
- src/main/webapp/js/normal.js
> 修改了教学互动子页面链接的一些问题

- src/main/webapp/html/eduManageDetail-1.html
- src/main/webapp/html/eduManageDetail-2.html
- src/main/webapp/html/eduManageDetail-3.html
- src/main/webapp/html/eduManageDetail-4.html
- src/main/webapp/html/eduManageDetail-5.html
- src/main/webapp/html/scienceStudy.html
- src/main/webapp/js/normal.js
- src/main/webapp/style/scienceStudy/scienceStudy-1.css
> 完成教学管理界面设计

- docs/demand-specification.md
> 填写表1 客户端的功能需求

- src/main/webapp/html/eduManageDetail-1.html
- src/main/webapp/html/eduManageDetail-2.html
- src/main/webapp/html/eduManageDetail-3.html
- src/main/webapp/html/eduManageDetail-4.html
- src/main/webapp/html/eduManageDetail-5.html
- src/main/webapp/js/normal.js
- src/main/webapp/style/scienceStudy/normal.css
- src/main/webapp/style/scienceStudy/scienceStudy-1.css
> 更新教学管理界面内容

- src/main/webapp/html/eduManageDetail-1.html
- src/main/webapp/html/eduManageDetail-2.html
- src/main/webapp/html/eduManageDetail-3.html
- src/main/webapp/html/eduManageDetail-4.html
- src/main/webapp/html/eduManageDetail-5.html
- src/main/webapp/style/scienceStudy/scienceStudy-1.css
> 更新教学管理的首页底部导航栏

- src/main/webapp/html/educationalDetail-2.html
- src/main/webapp/html/educationalDetail-3.html
- src/main/webapp/html/educationalDetail-4.html
- src/main/webapp/html/educationalDetail-5.html
- src/main/webapp/html/educationalDetail-6.html
> 修复教学安排模块左侧导航栏跟随漏洞#54

- src/main/webapp/html/eduManageDetail-1.html
> 修复教学管理的首页底部导航栏漏洞 fix #49 

- src/main/webapp/style/scienceStudy/scienceStudy-1.css
> 更新教学管理界面布局颜色

- src/main/webapp/style/interaction/QQ.css
> 教学互动左边改成浅绿色

- src/main/webapp/html/index.html
- src/main/webapp/style/index/index.css
> 修改summary缩放问题

- src/main/webapp/style/index/index.css
> 修改summary右边距

- src/main/webapp/html/eduManageDetail-2.html
- src/main/webapp/html/eduManageDetail-3.html
- src/main/webapp/html/eduManageDetail-4.html
- src/main/webapp/html/eduManageDetail-5.html
- src/main/webapp/style/eduManage/eduManageDetail.css
- src/main/webapp/style/eduManage/normal.css
> 修复教学管理界面bug

- src/main/webapp/html/teachResDetail-5.html
- src/main/webapp/style/teachRes/teachResDetail-5.css
> 更新教学资源-实验任务界面 

- src/main/webapp/html/teachResDetail-1.html
- src/main/webapp/js/teachRes/teachResDetail-1.js
> 修正课程课件预览问题

- src/main/webapp/html/teachResDetail-1.html
- src/main/webapp/js/teachRes/teachResDetail-1.js
> 修改在线课件js，动态调整src

- src/main/webapp/js/teachRes/teachResDetail-1.js
> 修改teacherDetail-1.js

- src/main/webapp/html/teachResDetail-1.html
- src/main/webapp/html/teachResDetail-2-video.html
- src/main/webapp/html/teachResDetail-2.html
- src/main/webapp/style/teachRes/normal.css
- src/main/webapp/style/teachRes/teachResDetail-1.css
> 修改课程录像及首页表格

- src/main/webapp/html/teachResDetail-5.html
> 修改实验任务界面对齐方式

- src/main/webapp/html/teachResDetail-2-video.html
> 修复360浏览器无法全屏播放视频bug

- src/main/webapp/html/admin-index.html
- src/main/webapp/html/courseware-add.html
- src/main/webapp/html/courseware-list.html
- src/main/webapp/html/picture-show.html
> 修改教程课件后台界面 fix #119

- src/main/webapp/html/admin-index.html
- src/main/webapp/html/teachingVideo-add.html
- src/main/webapp/html/teachingVideo-list.html
> 添加教学录像的后台显示 fix #120

- src/main/java/service/TeachingExperimentMissionService.java
> 添加教学任务增删查后台代码

- src/main/java/web/controller/courseWareServlet.java
- src/main/webapp/html/index.html
- src/main/webapp/html/teachResDetail-1.jsp
- src/main/webapp/js/normal.js
>  有关教学课件的修改

- pom.xml
- src/main/java/dao/IResourceManageDao.java
- src/main/java/dao/Impl/ResourceManageDaoImpl.java
- src/main/java/domian/Message.java
- src/main/java/service/IResourceManageService.java
- src/main/java/service/Impl/ResourceManageServiceImpl.java
- src/main/java/tools/PageInformation.java
- src/main/java/tools/Tool.java
- src/main/java/web/controller/courseWareServlet.java
- src/main/webapp/html/teachResDetail-1.jsp
- src/main/webapp/js/teachRes/teachResDetail-1.js
> 希望哪位大佬可以帮我改改翻页以及资源根据路径获取

- src/main/java/web/controller/experimentalTaskServlet.java
> 添加实验任务servlet增删改查

- pom.xml
- src/main/webapp/html/teachResDetail-5.jsp
pom.xml添加了jsp相关的资源，添加实验任务jsp页面
> 添加了jsp相关的jar包，添加实验任务jsp页面

- src/main/java/web/controller/experimentalTaskServlet.java
> 更新实验任务servlet

- src/main/webapp/admin/index.html
> 修改管理界面css相对路径bug

- src/main/java/service/Impl/ResourceManageServiceImpl.java
- src/main/java/tools/Tool.java
- src/main/java/web/controller/courseWareServlet.java
- src/main/webapp/html/bottom.jsp
- src/main/webapp/html/copyright.jsp
- src/main/webapp/html/educationalDetail-1.html
- src/main/webapp/html/teachResDetail-1.jsp
- src/main/webapp/html/top.jsp
- src/main/webapp/js/normal.js
- src/main/webapp/js/teachRes/teachResDetail-1.js
> 前台的翻页、预览、下载功能完成（注意使用绝对路径）

- src/main/java/dao/Impl/ResourceManageDaoImpl.java
- src/main/java/service/Impl/ResourceManageServiceImpl.java
- src/main/java/tools/Tool.java
- src/main/java/web/controller/experimentalTaskServlet.java
- src/main/webapp/html/teachResDetail-5.jsp
- src/main/webapp/js/normal.js
- src/main/webapp/js/teachRes/teachResDetail-5.js
完成实验任务分页显示，修改Tool.getPageInformation()函数：默认排序为顺序，默认排序字段为id
> 完成实验任务分页显示

- src/main/java/web/controller/courseWareServlet.java
- src/main/webapp/admin/courseWare/courseWare-list.jsp
- src/main/webapp/admin/index.html
>  教学课件后台的前端显示

- src/main/webapp/admin/courseWare/courseWare-list.jsp
> 后台课件jsp页面修改

- src/main/webapp/html/index.jsp
- src/main/webapp/html/left.jsp
- src/main/webapp/html/teachResDetail-1.jsp
- src/main/webapp/html/teachResDetail-2-video.jsp
- src/main/webapp/html/teachResDetail-2.jsp
- src/main/webapp/html/teachResDetail-3.jsp
- src/main/webapp/html/teachResDetail-4.jsp
- src/main/webapp/html/teachResDetail-5.jsp
- src/main/webapp/html/top.jsp
将top、left、bottom、copyright提出做公共jsp
> 将top、left、bottom、copyright提出做公共jsp

- src/main/webapp/admin/video/teachingVideo-add.jsp
- src/main/webapp/admin/video/teachingVideo-list.jsp
- src/main/webapp/html/teachResDetail-2-video.jsp
- src/main/webapp/html/teachResDetail-2.jsp
现在的删除只是删除数据库数据，为能够在服务器资源中删除文件。编辑功能还没。批量删除没。
>  初步做了教学录像前后台操作。todo:真删除，编辑，批量删除。

- src/main/webapp/html/bottom.jsp
> 一组修改bottom.jsp
